on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: RTX4000
    outputs:
     stylegan2:
        type: volume
    uses: git-checkout@v1
    with:
      # url: https://github.com/gradient-ai/stylegan2.git
      url: context.event.github.url
      ref: context.event.github.ref
  Training:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
    inputs:
      stylegan2: CloneRepo.outputs.stylegan2
    outputs:
      generatedFaces:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        cd inputs
        python run_training.py --num-gpus=8 --data-dir=~/datasets --config=config-f \
        --dataset=ffhq --mirror-augment=true
      image: tensorflow/tensorflow:1.14.0-gpu-py3
